name: Get Fresh Proxy

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug

env:
  ACCESS_CODE: ${{ secrets.ACCESS_CODE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        curl -H ${{secrets.AUTH}} -s -L ${{secrets.PATH_TEMPLATE}} -o template.md
        curl -H ${{secrets.AUTH}} -s -L ${{secrets.PATH_UPDATE}} -o update.sh
        chmod +x update.sh
        (echo -n '{"lastUpdated": "'; echo -n $(date); echo -n '", "proxies": '; cat proxylist.json; echo -n "}") > raw.json
    - run: ./update.sh
    - run: |
        rm template.md update.sh
    - run: |
        git config user.email ${{ secrets.GIT_EMAIL }}
        git config user.name ${{ secrets.GIT_USERNAME }}
        git add .
        git commit -am "Updated"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
